name: MCClassifieds
main: me.becja10.MCClassifieds.MCClassifieds
author: 10becja
version: 1.0
description: An economy plugin that allows players to place requests for items
depend: [Vault, Essentials]
commands:
  mcc:
    description: displays commands for this plugin
    usage: /<command>
  mccadmin:
    description: reloads the plugin and all configs
    usage: /<command>
  mccrequest:
    description: Allows for setting requests ingame. The command will start a chat wizard to help create the request.
    usage: /<command>
  mcclist:
    description: Shows all active requests. If 'mine' or another player's name is provided, shows all requests related to them.
    usage: /<command> (mine|player name) [page number]
  mccfulfill:
    description: Completes a request.
    usage: /<command> <id>
  mccget:
    description: Once a request is fulfilled, this will give you the items. Use /mcclist mine to get the right id.
    usage: /<command> <id>
  mcccancel:
    description: Cancels a request. To cancel your own request, omit player name
    usage: /<command> (player name) <id>